services:
  - type: web
    env: static
    name: portfo-soldado
    rootDir: Portfo
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
