services:
  - type: web
    runtime: static
    name: portfo-soldado
    rootDir: Portfo
    buildCommand: npm install && npm run build
    staticPublishPath: Portfo/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
